Added the 'staging' dependency module
puppetlabs-seteam/control-repo pull request #169
Opened 2020-09-01 16:04 UTC by rajeshr264

The staging module is need by site-modules/profile/manifests/app/cloudshop/sqlserver/staging.pp. The staging module is deprecated. However, the 'staging' module's replacement module 'archive' is not a drop in replacement. Keeping it simple for now & just adding the 'staging' module to keep the CloudShop app working, to demo SqlServer & IIS. We should move the CloudShop app into a seperate module and use CD4PE Module feature to build it out.

2020-09-03 23:25 UTC, reidmv requested changes
Seems reasonable to me. Given that it was originally removed for being deprecated, it might be best to include a comment acknowledging that it is deprecated, and indicating what TODO is required before it can be removed again.

2020-09-08 17:57 UTC, rajeshr264 commented
Hi @reidmv I have added a TODO section in the Puppetfile above the 'staging' module line.

2020-09-08 18:44 UTC, reidmv approved these changes
LGTM 👍

2020-09-09 23:47 UTC, rajeshr264 commented
added staging module to enable Cloudshop app to work.

2020-09-09 23:47 UTC, merged